### ISSUE TITLE
Wiki - Getting Started

### ISSUE THREAD

**Issue by Scrivener07** [chesko256/LilacFO4#2]
It seems its impossible for me to do a pull request on the wiki without different permissions. Sorry for the file attachment. Download [1.-Getting-Started.txt](https://github.com/chesko256/LilacFO4/files/801065/1.-Getting-Started.txt)

The examples on the [Getting Started](https://github.com/chesko256/LilacFO4/wiki/1.-Getting-Started) page do not compile with the FO4 compiler. I added the bool return type so that `describe` and `it` will accept the function parameters. I also added a few words about this to the [Its just functions](https://github.com/chesko256/LilacFO4/wiki/1.-Getting-Started#its-just-functions) section.

The exact compiler errors for `describe` and `it` were `type mismatch on parameter 2 - cannot pass a void to a bool`.

**Comment by chesko256** [comment]
Thanks!

**Comment by chesko256** [comment]
I didn't take your changes exactly, but I added a more descriptive note at the bottom of the page about the differences between the Skyrim and Fallout 4 versions, and linked to a correct Fallout 4 example.

**Comment by chesko256** [comment]
I'm dumb; I forgot that these were split across two separate repos, so it would make sense to have Fallout 4-specific data on the page. I incorporated your syntactical changes as well as some of my own to the examples. Thanks again.
